import 'package:chewie/chewie.dart' show Subtitle, Subtitles;
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:video_player/video_player.dart'
    show Caption, WebVTTCaptionFile;

/// Loads a lesson's captions from the bundled WebVTT assets.
///
/// Captions are generated by `tools/transcribe/` and shipped as assets rather
/// than fetched from R2, so they need no CORS setup and are reviewable in a diff.
///
/// Lessons are captioned incrementally, so a missing file is expected and must
/// never break playback: [load] returns `null` and Chewie simply omits its
/// captions toggle, leaving the player exactly as it was before.
class CaptionLoader {
  const CaptionLoader._();

  /// Matches the naming used by `tools/transcribe/transcribe.py`.
  static String assetPath(String topicKey, String curriculumKey) =>
      'assets/captions/${topicKey}__$curriculumKey.vtt';

  static Future<Subtitles?> load(String topicKey, String curriculumKey) async {
    if (topicKey.isEmpty || curriculumKey.isEmpty) return null;

    final String path = assetPath(topicKey, curriculumKey);
    String raw;
    try {
      raw = await rootBundle.loadString(path);
    } catch (_) {
      // No captions for this lesson yet. Not an error worth surfacing.
      return null;
    }

    try {
      final List<Caption> captions = WebVTTCaptionFile(raw).captions;
      if (captions.isEmpty) return null;
      return Subtitles(
        captions
            .map(
              (Caption c) => Subtitle(
                index: c.number,
                start: c.start,
                end: c.end,
                text: c.text,
              ),
            )
            .toList(growable: false),
      );
    } catch (error) {
      // The asset exists but is malformed — that IS a real problem, so say so
      // in debug instead of silently showing no captions.
      debugPrint('Malformed captions at $path: $error');
      return null;
    }
  }
}
