// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdq8QD00AVwIgVCP66RfUq_0X14mU5HlE',
    appId: '1:437357962430:web:6f6c1de7a52ac712eb6aef',
    messagingSenderId: '437357962430',
    projectId: 'vera-a4111',
    authDomain: 'vera-a4111.firebaseapp.com',
    databaseURL: 'https://vera-a4111-default-rtdb.firebaseio.com',
    storageBucket: 'vera-a4111.firebasestorage.app',
    measurementId: 'G-WNJG5JL34H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNJAkRB6cQ_7bQhNDk_8R3ktlgD_PlFc',
    appId: '1:437357962430:android:10202b4fb3e20400eb6aef',
    messagingSenderId: '437357962430',
    projectId: 'vera-a4111',
    databaseURL: 'https://vera-a4111-default-rtdb.firebaseio.com',
    storageBucket: 'vera-a4111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-mAthwyT_Q3w-xGg-Sp1RjXt7uPSUVU',
    appId: '1:437357962430:ios:218178fd014f5178eb6aef',
    messagingSenderId: '437357962430',
    projectId: 'vera-a4111',
    databaseURL: 'https://vera-a4111-default-rtdb.firebaseio.com',
    storageBucket: 'vera-a4111.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-mAthwyT_Q3w-xGg-Sp1RjXt7uPSUVU',
    appId: '1:437357962430:ios:218178fd014f5178eb6aef',
    messagingSenderId: '437357962430',
    projectId: 'vera-a4111',
    databaseURL: 'https://vera-a4111-default-rtdb.firebaseio.com',
    storageBucket: 'vera-a4111.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdq8QD00AVwIgVCP66RfUq_0X14mU5HlE',
    appId: '1:437357962430:web:c87026026ba5d0f1eb6aef',
    messagingSenderId: '437357962430',
    projectId: 'vera-a4111',
    authDomain: 'vera-a4111.firebaseapp.com',
    databaseURL: 'https://vera-a4111-default-rtdb.firebaseio.com',
    storageBucket: 'vera-a4111.firebasestorage.app',
    measurementId: 'G-VM6C4P0XWD',
  );
}
