name: Deploy Flutter Web

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Change to app directory
        run: cd coolapp

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./coolapp

      - name: Build Flutter web app
        run: |
          flutter build web --release \
            --base-href / \
            --csp \
            --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        working-directory: ./coolapp 

      - name: Add .nojekyll file
        run: touch ./coolapp/build/web/.nojekyll

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
