name: Deploy Flutter Web

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true 

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./coolapp

      - name: Build Flutter web with HTML renderer
        run: flutter build web --web-renderer html --release --base-href /
        working-directory: ./coolapp

      - name: Add .nojekyll file
        run: touch ./coolapp/build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coolapp/build/web
          publish_branch: gh-pages